oauth_token = "SJU_heVER1FUSZi8qpTDGqbm9LDPiSIHh2gedUK9tkw.SsOXYSW7ocsd97e4zPffUbUdZLgUO89RdjuvmuNdI_s"
expiration_time = "2025-11-15T19:56:44.693Z"
refresh_token = "nDqQrVhT6W0nKK2ezRkaDEbQEL9su4Vz9ygh3zMD5G8.2YT3pXaqKCtaQCJtEazLcoxaPbfBkL1dpge5xLaBEMs"
scopes = [
  "account:read",
  "user:read",
  "workers:write",
  "workers_kv:write",
  "workers_routes:write",
  "workers_scripts:write",
  "workers_tail:read",
  "d1:write",
  "pages:write",
  "zone:read",
  "ssl_certs:write",
  "ai:write",
  "queues:write",
  "pipelines:write",
  "secrets_store:write",
  "containers:write",
  "cloudchamber:write",
  "connectivity:admin",
  "offline_access"
]
